### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by ue71603** [SIRI-CEN/SIRI#59]
OJP includes geo locations from Datex II (DATEXIISchema_1_0_1_0.xsd) and SIRI (siri_utility\siri_location-v2.0.xsd). 
Is the Altitude in meter above sea-level something that we would like to store as well?. In more complex stops / locations this might be interesting.

![image](https://user-images.githubusercontent.com/24227470/94344590-c80a3e00-0020-11eb-9376-1fc20e77b16a.png)

(Comes from OJP: https://github.com/VDVde/OJP/issues/66)

**Comment by haeckerbaer** [comment]
Was solved with [CR081](https://github.com/SIRI-CEN/SIRI/pull/64/commits/05df38dc7053a0fcef0be1b34d681d0bc8a9d968#diff-ccbcf560a0919b14ff723a4d9bf6237c7774dbf17903df6e5629957328787d9cR156) and the introduction of FlexibleArea
