### ISSUE TITLE
xsd/xml/xml.xsd contains an outdated version leading to validation errors

### ISSUE THREAD

**Issue by sgrossberndt** [SIRI-CEN/SIRI#67]
https://github.com/SIRI-CEN/SIRI/blob/integration/xsd/xml/xml.xsd refers to an old version of the xml namespace definition and contains an enumeration with restrictions for the `lang` attribute. Those restrictions lead to validation errors if `xml:lang="de"` is used as this outdated version requires capital letters: `xml:lang="DE"`
The newer version https://www.w3.org/2005/08/xml.xsd does no longer contain that restriction, the file `xsd/xml/xml.xsd` should be updated with its content.

**Comment by prirey** [comment]
Thanks for this remark. I support this update.

We have to keep in mind that all XML Schema references such as xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
also have to be updated with this change.

w3 org remarks in https://www.w3.org/2005/08/xml.xsd that the content in http://www.w3.org/2001/xml.xsd is the same as in https://www.w3.org/2005/08/xml.xsd.

**Comment by prirey** [comment]
Hi @sgrossberndt 
I've just updated the content of xml.xsd according to http://www.w3.org/2001/xml.xsd which is the same as 2005/08. Because we gain nothing with upgrading all schema references to 2005 I've left the references as they were.

Do you agree with the proposal in the pullrequest?

**Comment by sgrossberndt** [comment]
For me www.w3.org/2001/xml.xsd is not accessible, your proposed xml.xsd does not contain the same content as https://www.w3.org/2005/08/xml.xsd, e.g. it contains a reference to a (non-existing?) `<?xml-stylesheet href="../2008/09/xsd.xsl" type="text/xsl"?>`. Is this an even newer version of xml.xsd?

**Comment by prirey** [comment]
Hi Stephan, I updated the pullrequest with the content from https://www.w3.org/2009/01/xml.xsd (including the stylesheet mentioned) and added the reference in the folder struture where the xml schema is imported from. Hope this helps in future ;)

**Comment by sgrossberndt** [comment]
Yes, thanks!

**Comment by haeckerbaer** [comment]
Solved with merge of https://github.com/SIRI-CEN/SIRI/pull/72 and https://github.com/SIRI-CEN/SIRI/pull/70 respectively.
