### ISSUE TITLE
Missing/inconsistent elements in SIRI-VM concerning Occupancy v2.1 updates

### ISSUE THREAD

**Issue by Ulf9** [SIRI-CEN/SIRI#78]
I ran across some inconsistences in the new SIRI-VM regarding Occupancy in relation to what has been added in SIRI-ET.

In the same manner as a MonitoredCall has either an ExpectedDeparture or an ActualDepartureTime  it should have (optionally) either an ExpectedDepartureOccupancy or a RecordedDepartureOccupancy. 

Also RecordedDepartureOccupancy should be included under PreviousCalls

I suggest the following files with adjusted XML  are used so that we can keep SIRI-VM  in line with additions in SIRI-ET.
[siri_model_corrections.zip](https://github.com/SIRI-CEN/SIRI/files/6568526/siri_model_corrections.zip)

**Comment by haeckerbaer** [comment]
fixed via PullRequest #87
