### ISSUE TITLE
Critical bug in master (v2.0) 

### ISSUE THREAD

**Issue by syversenkr** [SIRI-CEN/SIRI#98]
On the master branch a <xsd:enumeration> tag is **incorrectly closed** for the value "heavySnowFall", making its ensuing <xsd:annotation> / <xsd:documentation> disallowed and thereby the whole SIRI XSD master branch invalid.

(I.e. the master branch XSD has been invalid since 2019...)

**Branch**
https://github.com/SIRI-CEN/SIRI/tree/master

**File** 
siri_situationReasons-v2.0.xsd ([https://github.com/SIRI-CEN/SIRI/blob/master/xsd/siri_model/siri_situationReasons-v2.0.xsd](https://github.com/SIRI-CEN/SIRI/blob/master/xsd/siri_model/siri_situationReasons-v2.0.xsd)) 

**Lines 1978-1981 (1982):** 

```
<xsd:enumeration value="heavySnowFall"/> 
<xsd:annotation>
  <xsd:documentation>TPEG Pti22_3 heavy snow fall.</xsd:documentation>
</xsd:annotation> 
```

Should have been:

```
<xsd:enumeration value="heavySnowFall">
  <xsd:annotation>
    <xsd:documentation>TPEG Pti22_3 heavy snow fall.</xsd:documentation>
  </xsd:annotation>
</xsd:enumeration>
```

_Even if this is fixed a long time ago on the currently default **integration** (v2.1) branch, the XSD should also be valid on the v2.0 (master) branch which will still be the per spec **official version** for a while longer._

**Comment by syversenkr** [comment]
Additionally, the same bug affects prior tag [v2.0q](https://github.com/SIRI-CEN/SIRI/releases/tag/v2.0q) (September 16th 2019)

_However, prior tags [v2.0o](https://github.com/SIRI-CEN/SIRI/releases/tag/v2.0o) and [v2.0n](https://github.com/SIRI-CEN/SIRI/releases/tag/v2.0n) (both September 13th 2019) are **not** affected by this bug and validate fine._

**Comment by skinkie** [comment]
Just stumbled on this as well. https://github.com/SIRI-CEN/SIRI/tree/2.0q has a fix.
Having a branch makes it easier for submodules as well.
